"""Stage 1 - research.

claude mode: Claude researches the topic with live web search, then a second
structured call turns its notes into research.json, keeping confirmed facts
(backed by a cited source) apart from uncertain ones.

manual mode: you (or another tool) write research/research.json; this stage
validates it and renders research.md.
"""

from __future__ import annotations

import json

from ..llm import Claude
from ..project import Project
from ..schemas import Research, claude_schema

SYSTEM = (
    "You are the research desk for a premium documentary. Accuracy beats drama. "
    "Never invent statistics, quotations, events or sources. Every number needs a year and "
    "a source. If sources disagree or a claim is popular but weakly sourced, say so."
)


def _research_prompt(topic: str, topics: list[str]) -> str:
    bullet = "\n".join(f"- {t}" for t in topics)
    return (
        f"Research this documentary topic thoroughly using web search:\n\n{topic}\n\n"
        f"Cover each of these areas:\n{bullet}\n\n"
        "For each area, write concise factual notes with the source URL after each claim. "
        "Prefer primary and authoritative sources (government statistics offices, central banks, "
        "the World Bank and IMF, encyclopaedias, major newspapers, academic work). Collect the "
        "important statistics with their year. List popular claims you could not verify."
    )


def _structure_prompt(topic: str, notes: str, sources: list[dict], topics: list[str]) -> str:
    return (
        f"Topic: {topic}\n\nResearch notes:\n{notes}\n\nCited sources:\n"
        + json.dumps(sources, indent=1)
        + "\n\nConvert these notes into the research structure. Use exactly these section "
        f"topics in this order: {json.dumps(topics)}. Mark a fact 'confirmed' only when the notes "
        "cite a source for it; otherwise 'uncertain' with a note explaining why. Copy source URLs "
        "exactly. Do not add anything that is not in the notes. Set generated_by to 'claude'."
    )


def render_markdown(research: Research) -> str:
    lines = [f"# Research: {research.topic}", "", f"_Generated by: {research.generated_by}_", ""]
    for section in research.sections:
        lines += [f"## {section.topic}", ""]
        for f in section.facts:
            mark = "✅" if f.status == "confirmed" else "⚠️ uncertain"
            src = " ".join(f"[{i + 1}]({u})" for i, u in enumerate(f.sources))
            note = f" — _{f.note}_" if f.note else ""
            lines.append(f"- {mark} {f.claim} {src}{note}")
        lines.append("")
    if research.statistics:
        lines += ["## Key statistics", "", "| Statistic | Value | Year | Status | Source |", "|---|---|---|---|---|"]
        for s in research.statistics:
            lines.append(f"| {s.name} | {s.value} | {s.year} | {s.status} | {s.source} |")
        lines.append("")
    if research.sources:
        lines += ["## Sources", ""] + [f"- [{s.title or s.url}]({s.url})" for s in research.sources]
    return "\n".join(lines) + "\n"


def run_research(project: Project) -> Research:
    out_json = project.path("research", "research.json")
    topic = project.config.get_path("project.topic")
    topics = project.config.get_path("research.topics", [])

    if project.config.get_path("llm.provider") == "claude" and not out_json.exists():
        claude = Claude(project, "research")
        project.log("research", "researching with Claude + web search")
        notes = claude.research(SYSTEM, _research_prompt(topic, topics))
        project.path("research", "notes.md").write_text(notes.text)
        data = claude.json(SYSTEM, _structure_prompt(topic, notes.text, notes.sources, topics),
                           claude_schema(Research), what="research structuring")
        research = Research.model_validate(data)
        out_json.write_text(research.model_dump_json(indent=2))
    elif out_json.exists():
        research = Research.model_validate_json(out_json.read_text())
    else:
        raise FileNotFoundError(
            f"llm.provider is 'manual' and {project.rel(out_json)} does not exist. "
            "Write it (see docs/formats.md) or set llm.provider: claude."
        )

    confirmed = sum(f.status == "confirmed" for s in research.sections for f in s.facts)
    uncertain = sum(f.status == "uncertain" for s in research.sections for f in s.facts)
    missing = [t for t in topics if t not in {s.topic for s in research.sections}]
    if missing:
        project.log("research", f"WARNING: research has no section for: {', '.join(missing)}")
    project.path("research", "research.md").write_text(render_markdown(research))
    project.log("research", f"{confirmed} confirmed facts, {uncertain} uncertain, "
                            f"{len(research.sources)} sources")
    return research
